dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
          - COMPILERCXX=g++-4.9
          - COMPILERC=gcc-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
          - COMPILERCXX=g++-5
          - COMPILERC=gcc-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
          - COMPILERCXX=g++-6
          - COMPILERC=gcc-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
          - COMPILERCXX=clang++-3.6
          - COMPILERC=clang-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env:
          - COMPILERCXX=clang++-3.7
          - COMPILERC=clang-3.7
os:
    - linux

# install "python3" used in the test script
before_install:
    - sudo apt-get install python3

# build and test
script:
    - CC=$COMPILERC
    - CXX=$COMPILERCXX
    - $CC --version
    - make CI=1
    - make test
