dist: trusty
language: cpp

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.6
        - llvm-toolchain-precise-3.7
      packages:
        - g++-4.9
        - g++-5
        - g++-6
        - clang-3.6
        - clang-3.7

matrix:
  include:
    - compiler: gcc
      env: CC=gcc-4.9
    - compiler: gcc
      env: CC=gcc-5
    - compiler: gcc
      env: CC=gcc-6
    - compiler: clang
      env: CC=clang-3.6
    - compiler: clang
      env: CC=clang-3.7
os:
    - linux

# install "python3" used in the test script
before_install:
    - sudo apt-get install python3

# build and test
script:
    - $CC --version
    - make CI=1
    - make test
